<a href="https://colab.research.google.com/github/santoshtiwari41/Tensors-in-pytorch/blob/main/Tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#............................ Creating Tensors..........................................

In [4]:
# import library
import torch

In [5]:
# Scalar (0-dimensional tensor)
scalar = torch.tensor(3.14)
print("Scalar:", scalar)
print("Scalar Shape:", scalar.shape)

Scalar: tensor(3.1400)
Scalar Shape: torch.Size([])


In [6]:
# Vector (1-dimensional tensor)
vector = torch.tensor([1.0, 2.0, 3.0])
print("\nVector:", vector)
print("Vector Shape:", vector.shape)



Vector: tensor([1., 2., 3.])
Vector Shape: torch.Size([3])


In [7]:
# Matrix (2-dimensional tensor)
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("\nMatrix:\n", matrix)
print("Matrix Shape:", matrix.shape)



Matrix:
 tensor([[1., 2.],
        [3., 4.]])
Matrix Shape: torch.Size([2, 2])


In [8]:
# Higher-dimensional tensor (3D tensor)
tensor_3d = torch.rand(3, 2, 4)  # Random values in a 3x2x4 tensor
print("\n3D Tensor:\n", tensor_3d)
print("3D Tensor Shape:", tensor_3d.shape)


3D Tensor:
 tensor([[[0.8969, 0.3541, 0.2836, 0.8298],
         [0.6364, 0.9919, 0.4644, 0.4258]],

        [[0.3105, 0.0105, 0.6976, 0.2421],
         [0.7248, 0.1416, 0.6709, 0.0588]],

        [[0.0349, 0.9710, 0.9643, 0.6729],
         [0.5786, 0.5939, 0.3145, 0.2885]]])
3D Tensor Shape: torch.Size([3, 2, 4])


In [9]:
#......................................................Tensor Operations..........................................

In [10]:
# Element-wise operations
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])


In [11]:
# Addition
print("\nAddition:", a + b)



Addition: tensor([5, 7, 9])


In [12]:
# Multiplication
print("Multiplication:", a * b)


Multiplication: tensor([ 4, 10, 18])


In [13]:
# Reduction (Sum, Mean)
print("Sum:", a.sum())
print("Mean:", a.float().mean())  # Convert to float for mean

Sum: tensor(6)
Mean: tensor(2.)


In [14]:
#................................................ Manipulating Tensors......................................

In [15]:
# Reshaping a tensor
tensor = torch.arange(12)  # Creates a tensor with values [0, 1, ..., 11]
reshaped_tensor = tensor.view(3, 4)  # Reshape into a 3x4 tensor
print("\nReshaped Tensor:\n", reshaped_tensor)



Reshaped Tensor:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [16]:
# Slicing
print("First row:", reshaped_tensor[0])
print("Column 2:", reshaped_tensor[:, 1])


First row: tensor([0, 1, 2, 3])
Column 2: tensor([1, 5, 9])


In [17]:
# Adding a dimension
expanded_tensor = tensor.unsqueeze(0)  # Adds a dimension at axis 0
print("Expanded Tensor Shape:", expanded_tensor.shape)


Expanded Tensor Shape: torch.Size([1, 12])


In [18]:
# Transposing (swap axes)
transposed_tensor = reshaped_tensor.T
print("Transposed Tensor:\n", transposed_tensor)

Transposed Tensor:
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
